apiVersion: integration/v1
kind: Trigger
name: json
version: 1
summary: Pass through JSON data
description: |
  This trigger passes through a JSON object sent as an HTTP request body as a
  Relay event.

responders:
- webhook

schemas:
  spec: {}
  event:
    $schema: 'http://json-schema.org/draft-07/schema#'
    type: object

examples:
- summary: Pass arbitrary data through to a Relay workflow
  content:
    apiVersion: v1
    kind: Trigger
    name: pagerduty-incident
    source:
      type: webhook
      image: relaysh/stdlib-trigger-json
    binding:
      parameters:
        foo: !Data foo

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/stdlib-trigger-json
