apiVersion: "integration/v1"
kind: "Step"
name: "relay-template-renderer"
channel: "stable"
version: "v20200408"
summary: "Render a go text/template with a JSON input"
build:
  apiVersion: "build/v1"
  kind: "Docker"
publish:
  repository: "awrenn53/relay-template-renderer"
schemas:
  spec:
    source: "file"
    file: "spec.schema.json"
schemas:
  spec:
    $schema: "http://json-schema.org/draft-07/schema#"
    type: object
    properties:
      template:
        type: "string"
        description: "The template to fill out with the arguments - uses go's template/text syntax"
      parameters:
        type: "string"
        description: "JSON Object to call template.Render with for the above template"
      output:
        type: "string"
        description: "The variable name to output the rendered template to - useful for matching input of next stage"
 outputs:
   $schema: "http://json-schema.org/draft-07/schema#"
    type: "object"
    properties:
      result:
        type: "string"
        description: "The rendered template"
exampLes:
  - summary: "Transform a payload in a rendered string"
    content:
      apiVersion: "v1"
      kind: "Step"
      name: "Render template"
      image: "awrenn53/relay-template-renderer"
      spec:
        parameters: '{"from": "ACW"}'
        template: "Hello world! From, {.from}"
owner:
  name: "Andrew Wrenn"
  email: "awrenn53@gmail.com"
